# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Book-Wasta"
license = "GPL3"
licenselink = "https://github.com/wasta-linux/hugo-book-wasta/blob/master/LICENSE"
description = "Hugo theme  using Arc color scheme and Ubuntu fonts based on hugo-book theme"
homepage = "https://github.com/wasta-linux/hugo-book-wasta"
tags = ["responsive", "clean", "documentation", "docs", "flexbox", "search", "mobile"]
features = []
min_version = "0.55"

[author]
  name = "Rik Shaw"
  homepage = "https://github.com/rik-shaw/"
